services:
  db:
    image: postgres:15
    container_name: h3_travel_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: h3_travel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: h3_travel_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env.development
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:community
    container_name: h3_sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - TZ=Europe/Paris 
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9000:9000"

  grafana:
    image: grafana/grafana:latest
    container_name: h3_grafana
    restart: always
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=Europe/Paris
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    container_name: h3_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: h3_node_exporter
    restart: always
    ports:
      - "9100:9100"

volumes:
  db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  grafana_data:
  prometheus_data:
