global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["h3_prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["h3_node_exporter:9100"]

  - job_name: "backend"
    static_configs:
      - targets: ["h3_travel_backend:8080"]
